import _ from 'lodash';

export default _.mapKeys([
	'APP_SAVE_USER',
    'PATIENTS_ADD',
    'PATIENTS_UPDATE_PRESCRIPTION_REQUEST_STATUS',
    'PRESCRIPTIONS_ADD',
    'PRESCRIPTIONS_ADD_SHARED_WITH',
    'PRESCRIPTIONS_REQUESTS_ADD',
    'PRESCRIPTIONS_REQUESTS_REMOVE'
]);
